spring.application.name=rag-spring

server.port=8080

openai.api-key=API_KEY
openai.chat-model=gpt-4o-mini
openai.embedding-model=text-embedding-3-small

rag.chunk-size=500
rag.chunk-overlap=50
rag.max-results=5
rag.min-score=0.3